# Source: https://github.com/starkat99/appveyor-rust/

# Rust needs at least Visual Studio 2013 Appveyor OS for MSVC targets.
image: Visual Studio 2015

environment:
  global:
    PROJECT_NAME: eakio
  matrix:
    # Stable channel
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: stable
      MSYS2_BITS: 64
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS2_BITS%\bin
  - rustc -Vv
  - cargo -V

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose
  - cargo test

before_deploy:
  # Generate artifacts for release
  - cargo build --release
  - mkdir staging
    # release file will look like 'fakio-client-v3.0-x86_64-pc-windows-msvc'
  - copy target\release\eakio.exe staging\eakio-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.exe
  - appveyor PushArtifact staging\eakio-%APPVEYOR_REPO_TAG_NAME%-%TARGET%.exe

deploy:
  description: 'Windows release'
  # All the exe artifacts will be deployed
  artifact: /.*\.exe/
  # Here's how:
  # - Go to 'https://github.com/settings/tokens/new' and generate a Token with only the
  # `public_repo` scope enabled
  # - Then go to 'https://ci.appveyor.com/tools/encrypt' and enter the newly generated token.
  # - Enter the "encrypted value" below
  auth_token:
    secure: nGbuoe8OaAJWvJtrlVVtInGArp0zvSRqR1jFaDYsjqI1IZK6IA6+pKVHnvL/Tuhz
  provider: GitHub
  # deploy when a new tag is pushed and only on the stable channel
  on:
    # channel to use to produce the release artifacts
    CHANNEL: stable
    appveyor_repo_tag: true

branches:
  only:
    # appveyor or github bug? if no develop, tag push build not run
    - develop
    # IMPORTANT Regex to match tags. Required, or appveyor may not trigger deploys when a new tag
    # is pushed. This regex matches semantic versions like v1.2.3-rc4+2016.02.22
    - /^v\d+\.\d+.*$/

# Disable caching, for now
#cache:
#  - '%USERPROFILE%\.cargo'
#  - 'target -> Cargo.lock'